<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:45:46 +0000
// --------------------------------------------------------------------------------

$l['nav_calendar'] = '캘린더';
$l['nav_viewevent'] = '일정 보기';
$l['nav_dayview'] = '일별 보기';
$l['nav_addevent'] = '일정 추가';
$l['nav_editevent'] = '일정 수정';
$l['nav_move_event'] = '일정 이동';
$l['calendar_disabled'] = '관리자에 의해 캘린더 기능이 사용 불가 설정되었습니다.';
$l['alt_month_1'] = '1월';
$l['alt_month_2'] = '2월';
$l['alt_month_3'] = '3월';
$l['alt_month_4'] = '4월';
$l['alt_month_5'] = '5월';
$l['alt_month_6'] = '6월';
$l['alt_month_7'] = '7월';
$l['alt_month_8'] = '8월';
$l['alt_month_9'] = '9월';
$l['alt_month_10'] = '10월';
$l['alt_month_11'] = '11월';
$l['alt_month_12'] = '12월';
$l['add_private_event'] = '비공개 이벤트 추가';
$l['add_public_event'] = '공개 이벤트 추가';
$l['calendar'] = '캘린더';
$l['jump_month'] = 'x월로 이동:';
$l['birthdays_on_day'] = '{1}일의 생일';
$l['birthdayhidden'] = '숨김';
$l['event'] = '이벤트';
$l['events'] = '이벤트들';
$l['add_event'] = '이벤트 추가';
$l['event_date'] = '이벤트 날짜:';
$l['event_recurring_start_date'] = '시작 날짜:';
$l['event_recurring_end_date'] = '끝 날짜:';
$l['event_recurring_repeat_days'] = '반복 날짜:';
$l['event_name'] = '이벤트 이름:';
$l['event_details'] = '이벤트 상세:';
$l['event_options'] = '옵션:';
$l['private_option'] = '<b>비공개</b> 당신만 이 이벤트를 볼 수 있습니다. (등록된 사용자만 열람 가능).';
$l['delete_option'] = '<b>삭제:</b> 이벤트 삭제.';
$l['post_event'] = '이벤트 공개';
$l['day_view'] = '날짜 보기';
$l['birthday'] = '생일';
$l['birthdays'] = '생일들';
$l['event_author'] = '이벤트 주최자:';
$l['edit_event'] = '이벤트 수정';
$l['view_event'] = '이벤트 보기';
$l['no_events'] = '이 날에는 아무 이벤트가 없습니다.<p><a href="calendar.php?action=addevent&amp;calendar={1}&amp;day={2}&amp;month={3}&amp;year={4}">이벤트 추가하기</a>.</p>';
$l['years_old'] = '{1} 살';
$l['alt_edit'] = '이 이벤트 수정';
$l['alt_delete'] = '이 이벤트 삭제';
$l['moderator_options'] = '관리자 옵션';
$l['approve_event'] = '이벤트 승인';
$l['unapprove_event'] = '이벤트 무시';
$l['move_event'] = '이벤트 옮기기';
$l['repeats_every_day'] = '매일 반복하기';
$l['repeats_every_x_days'] = '{1}일마다 반복';
$l['repeats_on_weekdays'] = '월요일에서 금요일마다 반복';
$l['every_week_on_days'] = '매주 {1}마다 반복';
$l['every_week'] = '매주 반복';
$l['every_x_weeks_on_days'] = '{1}주마다 <br />{2}에 반복';
$l['every_x_weeks'] = '{1} 주마다 반복';
$l['every_month_on_day'] = '매달 {1}일마다 반복<br />';
$l['every_x_months_on_day'] = '{2}달마다 {1}일에 반복<br />';
$l['every_month_on_weekday'] = '매달 {1} {2}에 반복<br />';
$l['every_x_months_on_weekday'] = '{3}달마다 {1} {2}에 반복<br />';
$l['weekday_occurance_1'] = '첫째';
$l['weekday_occurance_2'] = '둘째';
$l['weekday_occurance_3'] = '셋째';
$l['weekday_occurance_4'] = '넷째';
$l['weekday_occurance_last'] = '마지막';
$l['every_year_on_day'] = '매년 {1} {2}마다 반복';
$l['every_x_years_on_day'] = '{3}년마다 {1} {2}에 반복';
$l['every_year_on_weekday'] = '매년 {3}의 {1} {2}에 반복';
$l['every_x_year_on_weekday'] = '{4}년마다 {3}의 {1} {2}에 반복';
$l['delete_event'] = '이벤트 삭제';
$l['delete_q'] = '삭제하시겠습니까?';
$l['delete_1'] = '삭제하려면, 왼쪽에 체크하고 오른쪽에 버튼을 누르십시오.';
$l['delete_2'] = '<b>알림:</b> 이 행동은 되돌릴 수 없습니다.';
$l['delete_now'] = '바로 삭제';
$l['delete_no_checkbox'] = '이 이벤트는 "삭제" 가 확인되지 않았기 때문에 삭제되지 않았습니다.';
$l['jump_to_calendar'] = '캘린더로 가기:';
$l['select_calendar'] = '캘린더:';
$l['type_single'] = '당일 이벤트';
$l['type_ranged'] = '기간제 이벤트';
$l['enter_time'] = '시간:';
$l['start_time'] = '시작 시간:';
$l['end_time'] = '종료 시간:';
$l['timezone'] = '시간대:';
$l['ignore_timezone'] = '<strong>시간대 무시:</strong> 이 이벤트는 시청자의 시간대에 따릅니다.';
$l['repeats'] = '반복:';
$l['does_not_repeat'] = '반복하지 않음';
$l['repeats_daily'] = '매일';
$l['repeats_weekdays'] = '매주 평일마다 (Mon-Fri)';
$l['repeats_weekly'] = '주간';
$l['repeats_every'] = '마다 반복';
$l['day_or_days'] = '일간';
$l['week_or_weeks_on'] = '주간';
$l['repeats_monthly'] = '월간';
$l['repeats_yearly'] = '연간';
$l['repeats_on_day'] = '일에 반복';
$l['of_every'] = '마다 반복';
$l['month_or_months'] = '달';
$l['repeats_on_the'] = '에 반복';
$l['day_of_every'] = '매 일';
$l['repeats_on'] = '에 반복';
$l['every'] = '매';
$l['year_or_years'] = '연';
$l['of'] = '마다';
$l['move_to_calendar'] = '캘린더로 이동:';
$l['weekly_overview'] = '주간 일정';
$l['previous_week'] = '지난주';
$l['next_week'] = '다음주';
$l['first'] = '첫째';
$l['second'] = '둘째';
$l['third'] = '셋째';
$l['fourth'] = '넷째';
$l['last'] = '마지막';
$l['all_day'] = '종일';
$l['starts'] = '시작: ';
$l['finishes'] = '끝: ';
$l['error_incorrectday'] = '입력한 날짜가 없습니다. 다시 돌아가 다시 시도하십시오.';
$l['error_invalidevent'] = '지정한 이벤트가 잘못되었거나 없습니다.';
$l['invalid_calendar'] = '지정한 달력이 없습니다. 올바른 페이지를 방문하고 계십니까?';
$l['redirect_eventdeleted'] = '이벤트가 삭제되었습니다.<br />이제 달력으로 다시 이동됩니다.';
$l['redirect_eventupdated'] = '이벤트가 성공적으로 업데이트되었습니다.<br />이제 이벤트로 돌아갑니다.';
$l['redirect_eventadded'] = '이벤트가 성공적으로 추가되었습니다.<br />이제 이벤트로 전환됩니다.';
$l['redirect_eventadded_moderation'] = '이벤트가 성공적으로 추가되었지만 이벤트가 표시되기 전에 포럼 진행자의 조정이 필요합니다.<br />이제 일정으로 다시 이동됩니다.';
$l['redirect_eventunapproved'] = '이벤트가 승인되지 않았습니다.<br />이제 이벤트로 이동합니다.';
$l['redirect_eventapproved'] = '이벤트가 성공적으로 승인되었습니다.<br />이제 이벤트에 참여하게 됩니다.';
$l['redirect_eventmoved'] = '이벤트가 정상적으로 이동되었습니다.<br />이제 이벤트로 이동합니다.';
