<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:45:51 +0000
// --------------------------------------------------------------------------------

$l['contact'] = '연락처';
$l['contact_no_message'] = '보낼 메시지를 선택하지 않았습니다.';
$l['contact_no_subject'] = '제목을 입력해야 합니다.';
$l['contact_no_email'] = '유효한 이메일 주소를 입력해야 합니다.';
$l['contact_success_message'] = '메시지가 관리자에게 성공적으로 전송되었습니다.';
$l['contact_subject'] = '제목';
$l['contact_subject_desc'] = '메시지의 간단한 요약.';
$l['contact_message'] = '메시지';
$l['contact_message_desc'] = '문제점에 관한 구체적인 요약.';
$l['contact_email'] = '이메일';
$l['contact_email_desc'] = '답변을 드릴 수 있도록 이메일을 입력해 주십시오.';
$l['contact_send'] = '보내기';
$l['subject_too_long'] = '제목이 너무 깁니다. {1} 보다 짧은 문장을 입력해 주십시오 (현재 {2}).';
$l['message_too_short'] = '메시지가 너무 짧습니다. {1}보다 긴 문장을 입력해 주십시오 (현재 {2}).';
$l['message_too_long'] = '메시지가 너무 깁니다. {1}보다 짧은 문장을 입력해 주십시오 (현재 {2}).';
$l['error_stop_forum_spam_spammer'] = '죄송합니다, {1}가 도배 필터에 걸려 메시지가 전송될 수 없습니다.';
$l['error_stop_forum_spam_fetching'] = '죄송합니다. 도배 데이터베이스에 메시지를 대조하는 과정에 문제가 생겼습니다. 데이터베이스에 접근할 수 없습니다. 잠시 뒤 다시 시도하십시오.';
