<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:47:22 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = '제목이 너무 깁니다. 더 짧은 제목을 입력하십시오.';
$l['pmdata_code_no_subject'] = '[제목없음]';
$l['pmdata_missing_subject'] = '제목을 입력하지 않았습니다. 제목을 입력하십시오.';
$l['pmdata_missing_message'] = '내용을 입력하지 않았습니다. 내용을 입력하십시오';
$l['pmdata_message_too_long'] = '메시지가 너무 깁니다. {1}자보다 짧은 메시지를 입력하십시오 (현재 {2}자).';
$l['pmdata_invalid_recipients'] = '수신자 목록에 등록되지 않은 사용자가 있습니다. 다시 확인하십시오. 사용자: {1}명';
$l['pmdata_no_recipients'] = '메시지를 보낼 수신자를 선택하지 않았습니다. 수신자 목록에 최소 한명은 있어야 합니다.';
$l['pmdata_too_many_recipients'] = '한번에 최소 {1}명씩 메시지를 보낼 수 있습니다.';
$l['pmdata_recipient_is_ignoring'] = '{1}에게 차단되어 개인 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_has_buddy_only'] = '{1}과 친구가 아니기 때문에 개인 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_pms_disabled'] = '{1}가 개인 메시지를 차단해 놓았습니다. 이 사용자에게는 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_reached_quota'] = '{1}가 최대 개인 메시지 용량을 초과했기 때문에 더이상 메시지를 보낼 수 없습니다.';
$l['pmdata_pm_flooding'] = '메시지를 보내는 간격이 너무 짧습니다. {1}초 더 기다리십시오.';
$l['pmdata_pm_flooding_one_second'] = '메시지를 보내는 간격이 너무 짧습니다. 1초 더 기다리십시오.';
