<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:47:14 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = '부적절한 ID/비밀번호 조합입니다. <br /><br />비밀번호를 잊어버렸다면 <a href="member.php?action=lostpw">새로 발급받으십시오</a>.';
$l['logindata_invalidpwordusernameemail'] = '부적절한 이메일/비밀번호 조합입니다. <br /><br />비밀번호를 잊어버렸다면 <a href="member.php?action=lostpw">새로 발급받으십시오</a>.';
$l['logindata_invalidpwordusernamecombo'] = '부적절한 ID/비밀번호 또는 이메일/비밀번호 조합입니다 <br /><br />비밀번호를 잊어버렸다면 <a href="member.php?action=lostpw">새로 발급받으십시오</a>.';
$l['logindata_regimageinvalid'] = '입력한 코드가 일치하지 않습니다. 사진에 나타난 이미지를 그대로 입력하십시오.';
$l['logindata_regimagerequired'] = '로그인을 계속하려면 사진의 확인 코드를 입력하십시오. 사진에 나타난 그대로 입력하십시오.';
