<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:47:08 +0000
// --------------------------------------------------------------------------------

$l['eventdata_missing_name'] = '이벤트의 제목이 공백입니다. 이벤트 제목을 입력하십시오';
$l['eventdata_missing_description'] = '이벤트 설명이 공백입니다. 이벤트 설명을 입력하십시오';
$l['eventdata_invalid_start_date'] = '이벤트의 시작 날짜가 유효하지 않습니다. 해당 연월일이 유효한지 확인하십시오';
$l['eventdata_invalid_start_year'] = '이벤트는 다음 5년 안에 시작되어야 합니다. 목록에서 적절한 연도를 선택하십시오';
$l['eventdata_invalid_start_month'] = 'The start month you entered is not a valid month. Please enter a valid start month.
시작 월이 유효하지 않습니다. 유효한 시작월을 입력하십시오';
$l['eventdata_invalid_end_date'] = '이벤트 종료일이 유효하지 않습니다. 연월일이 적절한지 확인하십시오';
$l['eventdata_invalid_end_year'] = '이벤트는 다음 5년 안에 시작되어야 합니다. 목록에서 적절한 연도를 선택하십시오';
$l['eventdata_invalid_end_month'] = '종료월이 적절하지 않습니다. 적절한 종료월을 입력하십시오';
$l['eventdata_invalid_end_day'] = '종료일이 유효하지 않습니다. 종료일이 해당 달의 범위를 넘지 않는지 확인하십시오';
$l['eventdata_cant_specify_one_time'] = '이벤트 시작 시간을 지정하는 경우 이벤트 종료 시간을 입력해야 합니다.';
$l['eventdata_start_time_invalid'] = '입력한 시작 시간이 잘못되었습니다. 유효한 예는 12am, 12:01am, 00:01입니다.';
$l['eventdata_end_time_invalid'] = '입력한 종료 시간이 잘못되었습니다. 유효한 예는 오전 12시, 12시 1분, 00시 1분입니다.';
$l['eventdata_invalid_timezone'] = '이 이벤트에 대해 선택한 시간 영역은 잘못되었습니다.';
$l['eventdata_end_in_past'] = '이벤트 또는 시간 전에 이벤트 또는 시간 전에 이벤트입니다.';
$l['eventdata_only_ranged_events_repeat'] = '범위가 지정된 이벤트(시작 및 종료 날짜가 있는 이벤트)만 반복할 수 있습니다.';
$l['eventdata_invalid_repeat_day_interval'] = '날짜 반복 간격을 잘못 입력했습니다.';
$l['eventdata_invalid_repeat_week_interval'] = '잘못된 주간 반복 간격을 입력합니다.';
$l['eventdata_invalid_repeat_weekly_days'] = '이 이벤트가 발생할 평일을 선택하지 않았습니다.';
$l['eventdata_invalid_repeat_month_interval'] = '잘못된 달 간격을 입력합니다.';
$l['eventdata_invalid_repeat_year_interval'] = '잘못된 연도 반복 간격을 입력했습니다.';
$l['eventdata_event_wont_occur'] = '이벤트 반복 설정과 함께 시작 및 종료 시간을 사용하면 이 이벤트는 발생하지 않습니다.';
$l['eventdata_no_permission_private_event'] = '비공개 이벤트를 설정할 권한이 없습니다';
