<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:47:32 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = '하루에 할 수 있는 경고 수 제한에 도달했기 때문에 누구에게도 경고할 수 없습니다.<br /><br />하루에 할 수 있는 최대 경고 수는 {1}입니다.';
$l['warnings_error_invalid_user'] = '선택한 사용자가 존재하지 않습니다.';
$l['warnings_error_invalid_post'] = '선택한 게시물은 존재하지 않습니다.';
$l['warnings_error_cannot_warn_self'] = '자신의 경고 수준에 추가할 수 없습니다.';
$l['warnings_error_user_reached_max_warning'] = '이 사용자는 이미 최대 경고 수준에 도달했기 때문에 경고할 수 없습니다.';
$l['warnings_error_no_note'] = '이 경고에 대한 관리 참고 사항을 입력하지 않았습니다.';
$l['warnings_error_invalid_type'] = '잘못된 경고 유형을 선택했습니다.';
$l['warnings_error_cant_custom_warn'] = '사용자에게 사용자 정의 경고를 줄 수 있는 권한이 없습니다.';
$l['warnings_error_no_custom_reason'] = '사용자 정의 경고에 대한 이유를 입력하지 않았습니다.';
$l['warnings_error_invalid_custom_points'] = '이 사용자 주의 수준에 추가할 올바른 개수의 포인트를 입력하지 않았습니다. 0보다 크지만 {1}보다 크지 않은 숫자 값을 입력해야 합니다.';
$l['warnings_error_invalid_expires_period'] = '유효하지 않은 만료 유형을 입력했습니다.';
