<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:47:27 +0000
// --------------------------------------------------------------------------------

$l['userdata_missing_username'] = '사용자 이름을 입력하지 않았습니다. 하나를 입력하십시오.';
$l['userdata_banned_username'] = '입력한 사용자 이름이 등록되지 않았습니다. 다른 사용자 이름을 입력하십시오.';
$l['userdata_bad_characters_username'] = '입력한 사용자 이름에 잘못된 문자가 있습니다. 다른 사용자 이름을 입력하십시오.';
$l['userdata_invalid_username_length'] = '입력한 사용자 이름의 길이가 잘못되었습니다. {1}에서 {2}자 사이의 사용자 이름을 입력하십시오.';
$l['userdata_invalid_usertitle_length'] = '입력한 사용자 지정 사용자 제목의 길이가 잘못되었습니다. {1}자 이하의 제목을 입력하십시오.';
$l['userdata_username_exists'] = '입력한 사용자 이름이 이미 있습니다. 다른 사용자 이름을 입력하십시오.';
$l['userdata_invalid_password_length'] = '입력한 암호의 길이가 잘못되었습니다. {1}에서 {2}자 사이의 암호를 입력하십시오.';
$l['userdata_no_complex_characters'] = '입력한 암호가 충분히 복잡하지 않습니다. {1}자 이상의 암호를 입력하십시오. 대문자, 소문자 및 숫자가 포함된 암호를 입력하십시오.';
$l['userdata_passwords_dont_match'] = '확인으로 입력하신 비밀번호가 원래 비밀번호와 일치하지 않습니다. 비밀번호를 정확하게 확인해주세요.';
$l['userdata_bad_password_security'] = '입력한 비밀번호가 사용자 이름 또는 이메일 주소와 유사합니다. 더 강력한 비밀번호를 입력하십시오.';
$l['userdata_missing_email'] = '이메일 주소를 입력하지 않았습니다. 하나를 입력하십시오.';
$l['userdata_invalid_email_format'] = '입력한 이메일 주소가 잘못되었습니다. 올바른 이메일 주소를 입력하십시오.';
$l['userdata_emails_dont_match'] = '확인으로 입력하신 이메일 주소가 원래 주소와 일치하지 않습니다. 이메일 주소를 정확하게 확인해주세요.';
$l['userdata_banned_email'] = '입력하신 이메일 주소는 현재 사용할 수 없습니다. 다른 이메일 주소를 입력해 주세요.';
$l['userdata_email_already_in_use'] = '다른 회원이 이미 사용중인 이메일 주소를 입력했습니다. 다른 이메일 주소를 입력해주세요.';
$l['userdata_dob_required'] = '생년월일을 선택하지 않았습니다. 계속하려면 생년월일을 선택하십시오. 하지만 다른 사용자로부터 생일과 나이를 숨길 수 있습니다.';
$l['userdata_invalid_website'] = '입력한 웹 사이트 주소가 잘못되었습니다. 올바른 웹 사이트 주소를 입력하거나 필드를 비워 두십시오.';
$l['userdata_invalid_icq_number'] = '입력한 ICQ 번호가 잘못되었습니다. 올바른 ICQ 번호를 입력하거나 필드를 비워 두십시오.';
$l['userdata_invalid_birthday'] = '입력한 생일이 잘못되었습니다. 유효한 생일을 입력하거나 필드를 비워두십시오.';
$l['userdata_invalid_birthday_coppa'] = '나이를 확인하려면, 태어난 해를 입력하세요. 프로필 옵션에서 나이와 생년월일을 숨길 수 있습니다.';
$l['userdata_invalid_birthday_coppa2'] = '이 게시판의 회원이 되려면 13세 이상이어야 합니다. 관리자에게 문의하십시오.';
$l['userdata_invalid_birthday_privacy'] = '유효한 생일 개인 정보 보호 옵션을 선택하십시오.';
$l['userdata_conflicted_birthday_privacy'] = '나이를 생일 개인 정보로만 표시하려면 출생 연도를 지정해야 합니다.';
$l['userdata_invalid_referrer'] = '입력한 참조자가 없습니다. 존재하는 참조자를 입력하거나 필드를 비워두십시오.';
$l['userdata_invalid_language'] = '선택한 언어가 존재하지 않습니다. 존재하는 언어를 선택하십시오.';
$l['userdata_invalid_style'] = '선택한 스타일이 잘못되었습니다. 올바른 스타일을 선택하십시오.';
$l['userdata_away_too_long'] = '지정한 부재 이유가 너무 깁니다. 이 필드에는 최대 200자가 허용됩니다. 이 필드에서 {1}자를 제거하십시오.';
$l['userdata_missing_returndate'] = '지정한 반환 날짜에 하나 이상의 필드가 없습니다. 요일, 월 및 연도 필드를 입력했는지 확인하십시오.';
$l['userdata_missing_required_profile_field'] = '"{1}" 필드에 대한 옵션을 입력하지 않았습니다. 이 필드에 대한 값을 입력하거나 선택하십시오.';
$l['userdata_bad_profile_field_value'] = '"{1}" 필드에 올바른 값을 입력하지 않았습니다. 계속하기 전에 올바른 값을 입력하십시오.';
$l['userdata_bad_profile_field_values'] = '"{1}" 필드에 대한 올바른 옵션을 선택하지 않았습니다. 제시된 옵션에서 값을 선택하십시오.';
$l['userdata_max_limit_reached'] = '"{1}" 필드에 잘못된 문자 수를 입력했습니다. 이 필드는 {2}자 이내로 입력하십시오.';
$l['userdata_invalid_checkfield'] = '이 양식은 스팸봇에서 제출한 것으로 확인되었습니다. 만약 오류가 있는 경우 관리자에게 문의하시기 바랍니다.';
$l['userdata_invalid_postnum'] = '입력한 게시물 수가 잘못되었습니다. 올바른 게시물 수를 입력하거나 필드를 비워두십시오.';
$l['userdata_invalid_threadnum'] = '입력한 스레드 수가 잘못되었습니다. 올바른 스레드 수를 입력하거나 필드를 비워 두십시오.';
$l['userdata_too_many_sig_images'] = '죄송하지만 서명에 이미지가 너무 많이 포함되어 있어 업데이트할 수 없습니다. 계속하려면 서명에서 일부 이미지를 제거하십시오.';
$l['userdata_too_many_sig_images2'] = '<strong>참고:<strong> 서명의 최대 이미지 양은 {1}입니다.';
$l['userdata_sig_too_long'] = '서명이 너무 길어서 업데이트할 수 없습니다. 서명의 최대 길이는 {1}자입니다.';
$l['userdata_sig_remove_chars_plural'] = '{1}자를 제거하고 다시 시도하십시오.';
$l['userdata_sig_remove_chars_singular'] = '한 문자를 제거하고 다시 시도하십시오.';
