<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:58:06 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = '게시글 등록';
$l['moderated_by'] = '관리자:';
$l['nothreads'] = '죄송하지만 현재 이 포럼에 지정된 날짜 및 시간 제한 옵션이 있는 스레드가 없습니다.';
$l['nopermission'] = '죄송하지만 이 포럼에서 스레드를 볼 수 있는 권한이 없습니다.';
$l['search_forum'] = '포럼에서 검색:';
$l['thread'] = '게시글';
$l['author'] = '작성자';
$l['replies'] = '답글';
$l['views'] = '조회소';
$l['lastpost'] = '마지막 작성글';
$l['rating'] = '평점';
$l['prefix'] = '머릿말:';
$l['prefix_all'] = '머릿말: 아무/머릿말 없음';
$l['prefix_any'] = '머릿말: 아무 머릿말';
$l['prefix_none'] = '머릿말: 머릿말 없음';
$l['markforum_read'] = '이 포럼 읽음으로 표시';
$l['subscribe_forum'] = '이 포럼에 구독';
$l['unsubscribe_forum'] = '이 포럼 구독 해제';
$l['clear_stored_password'] = '저장된 포럼 비밀번호 삭제';
$l['sort_by_subject'] = '제목으로 정렬';
$l['sort_by_lastpost'] = '마지막 게시물로 정렬';
$l['sort_by_starter'] = '작성자로 정렬';
$l['sort_by_started'] = '시간순으로 정렬';
$l['sort_by_rating'] = '평점순으로 정렬';
$l['sort_by_replies'] = '답변순으로 정렬';
$l['sort_by_views'] = '조회수로 정렬';
$l['sort_order_asc'] = '오름차순';
$l['sort_order_desc'] = '내림차순';
$l['datelimit_1day'] = '오늘부터';
$l['datelimit_5days'] = '5일전부터';
$l['datelimit_10days'] = '10일전부터';
$l['datelimit_20days'] = '20일전부터';
$l['datelimit_50days'] = '50일전부터';
$l['datelimit_75days'] = '75일전부터';
$l['datelimit_100days'] = '100일전부터';
$l['datelimit_lastyear'] = '작년부터';
$l['datelimit_beginning'] = '처음부터';
$l['new_thread'] = '새 글';
$l['new_hot_thread'] = '인기글(새 글 포함)';
$l['posts_by_you'] = '본인이 포함된 글';
$l['no_new_thread'] = '새 글 없음';
$l['hot_thread'] = '인기글(새 글 없음)';
$l['closed_thread'] = '닫힌 글';
$l['goto_first_unread'] = '읽지 않은 첫 게시글로 이동';
$l['pages'] = '페이지:';
$l['pages_last'] = '마지막';
$l['users_browsing_forum'] = '이 포럼을 사용하는 이용자:';
$l['users_browsing_forum_guests'] = '게스트 수: {1}';
$l['users_browsing_forum_invis'] = '익명 사용자: {1}';
$l['delayed_moderation'] = 'Delayed Moderation';
$l['inline_thread_moderation'] = 'Inline Thread Moderation:';
$l['close_threads'] = '게시글 닫기';
$l['open_threads'] = '게시글 열기';
$l['stick_threads'] = '게시글 고정';
$l['unstick_threads'] = '게시글 고정 해제';
$l['soft_delete_threads'] = 'Soft Delete Threads';
$l['restore_threads'] = '게시글 복구';
$l['delete_threads'] = '게시글 영구 삭제';
$l['move_threads'] = '게시글 이동 / 복사';
$l['approve_threads'] = '게시글 승인';
$l['unapprove_threads'] = '게시글 승인 해제';
$l['inline_go'] = '이동';
$l['clear'] = '삭제';
$l['sub_forums_in'] = '\'{1}\'의 포럼';
$l['forum_rules'] = '{1} - 규칙';
$l['subforums'] = '하위 포럼:';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['forum_announcements'] = '포럼 공지';
$l['sticky_threads'] = '중요 게시글';
$l['normal_threads'] = '일반 게시글';
$l['icon_dot'] = '본인 게시글 포함. ';
$l['icon_no_new'] = '새 글 없음.';
$l['icon_new'] = '새 글.';
$l['icon_hot'] = ' 인기글.';
$l['icon_close'] = ' 닫힌 글.';
$l['attachment_count'] = '이 글은 첨부 파일이 1개 있습니다.';
$l['attachment_count_multiple'] = '이 글은 첨부파일이 {1}개 있습니다';
$l['rss_discovery_forum'] = '{1}의 최신 글';
$l['forum_unapproved_posts_count'] = '현재 이 포럼에 {1}개의 승인되지 않은 게시물이 있습니다.';
$l['forum_unapproved_post_count'] = '이 포럼에는 현재 승인되지 않은 게시물이 1개 있습니다.';
$l['forum_unapproved_threads_count'] = '현재 이 포럼에 {1}개의 승인되지 않은 스레드가 있습니다.';
$l['forum_unapproved_thread_count'] = '이 포럼에는 현재 승인되지 않은 스레드가 1개 있습니다.';
$l['thread_unapproved_posts_count'] = '이 스레드에는 현재 {1}개의 승인되지 않은 게시물이 있습니다.';
$l['thread_unapproved_post_count'] = '이 스레드에는 현재 승인되지 않은 게시물이 1개 있습니다.';
$l['page_selected'] = '이 페이지의 모든 <strong>{1}<strong> 스레드가 선택됩니다.';
$l['all_selected'] = '이 포럼의 모든 <strong>{1}<strong> 스레드가 선택되었습니다.';
$l['select_all'] = '이 포럼에서 모든 <strong>{1}<strong> 스레드를 선택합니다.';
$l['clear_selection'] = '지우기';
$l['deleted_thread'] = '삭제된 글';
$l['error_containsnoforums'] = '죄송하지만 현재 보고 있는 포럼에는 하위 포럼이 없습니다.';
$l['inline_edit_description'] = '(수정하려면 클릭 후 꾹 누르기)';
