<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 03:18:49 +0000
// --------------------------------------------------------------------------------

$l['d1_name'] = '사용자 등록';
$l['d1_desc'] = '사용자 등록에 대한 특전과 특권.';
$l['d1_document'] = '이 포럼의 일부 부분에서는 로그인하고 등록해야 할 수도 있습니다. 등록은 무료이며 완료하는 데 몇 분 정도 걸립니다.
<br /><br />등록을 권장합니다. 등록하면 메시지를 게시하고, 자신의 환경설정을 설정하고, 프로필을 유지할 수 있습니다.
<br /><br />일반적으로 등록이 필요한 기능 중 일부는 구독, 스타일 변경, 개인 메모장 액세스 및 포럼 구성원에게 이메일을 보내는 것입니다.';
$l['d2_name'] = '프로필 업데이트 중';
$l['d2_desc'] = '현재 기록 중인 데이터를 변경합니다.';
$l['d2_document'] = '체류 중 어느 시점에서 인스턴트 메신저 정보, 비밀번호 또는 이메일 주소와 같은 일부 정보를 업데이트해야 한다고 결정할 수 있습니다. 사용자 제어판에서 이 정보를 변경할 수 있습니다. 이 제어판에 액세스하려면 "사용자 CP"라는 제목의 대부분 페이지의 왼쪽 상단에 있는 링크를 클릭하기만 하면 됩니다. 여기에서 "사용자 프로필" 섹션에서 해당 링크를 선택하고 원하는 항목을 변경하거나 업데이트한 다음 페이지 하단에 있는 제출 버튼을 클릭하여 변경 사항을 적용합니다.';
$l['d3_name'] = 'MyBB의 쿠키 사용';
$l['d3_desc'] = '내 BB는 쿠키를 사용하여 등록에 대한 특정 정보를 저장할 수 있습니다.';
$l['d3_document'] = 'MyBB makes use of cookies to store your login information if you are registered, and your last visit if you are not.
<br /><br />Cookies are small text documents stored on your computer; the cookies set by this forum can only be used on this website and pose no security risk.
<br /><br />Cookies on this forum also track the specific topics you have read and when you last read them.
<br /><br />To clear all cookies set by this forum, you can click <a href="misc.php?action=clearcookies&amp;my_post_key={1}">here</a>.';
$l['d4_name'] = '로그인 및 로그아웃';
$l['d4_desc'] = '로그인 및 로그아웃 방법.';
$l['d4_document'] = '로그인할 때마다 사용자 이름과 비밀번호를 입력할 필요 없이 포럼을 찾을 수 있도록 컴퓨터에 쿠키를 설정합니다. 로그아웃하면 해당 쿠키가 지워져 다른 사람이 포럼을 찾을 수 없게 됩니다.
<br /><br /> 로그인하려면 포럼 오른쪽 상단에 있는 로그인 링크를 클릭하기만 하면 됩니다. 로그아웃하려면 같은 장소에 있는 로그아웃 링크를 클릭하세요. 로그아웃을 할 수 없는 경우 컴퓨터에 있는 쿠키를 지우면 동일한 효과가 나타납니다.';
$l['d5_name'] = '새 스레드 게시';
$l['d5_desc'] = '포럼에서 새 스레드를 시작합니다.';
$l['d5_document'] = '관심 있는 포럼에 가서 새 스레드(또는 주제)를 작성하려면 "새 스레드"라는 제목의 포럼 상단과 하단에 있는 버튼을 선택하기만 하면 됩니다. 관리자가 해당 포럼에 게시하는 것을 직원으로 제한하거나 포럼을 전체적으로 보관할 수 있으므로 모든 포럼에 새 스레드를 게시할 수 있는 권한이 없을 수 있습니다.';
$l['d6_name'] = '회신 게시';
$l['d6_desc'] = '포럼 내의 주제에 대한 회신.';
$l['d6_document'] = '방문하는 동안 회신할 스레드가 발생할 수 있습니다. 이렇게 하려면 스레드의 맨 아래 또는 맨 위에 있는 "새 회신" 단추를 클릭하기만 하면 됩니다. 관리자가 해당 포럼의 특정 개인에 대한 게시를 제한했을 수도 있습니다.
<br /><br />또한 포럼의 진행자가 사용자가 회신할 수 없는 스레드를 닫았을 수도 있습니다. 사용자가 진행자나 관리자의 도움 없이 이러한 스레드를 열 수 있는 방법은 없습니다.';
$l['d7_name'] = 'MyCode';
$l['d7_desc'] = 'MyCode를 사용하여 게시물을 향상시키는 방법에 대해 알아보십시오.';
$l['d7_document'] = 'You can use MyCode, also known as BB Codes to add effects or formatting to your posts. MyCodes are a simplified version of HTML and is used in a similar format to HTML tags which you may already be familiar with.
<br /><br />The table below is a quick guide of the MyCodes available:
<br /><br />
<table class="tborder" cellspacing="0" cellpadding="5" border="0" style="width:90%">
<tbody>
<tr>
<td class="tcat" style="width:55%"><span class="smalltext"><strong>Input</strong></span></td>
<td class="tcat" style="width:35%"><span class="smalltext"><strong>Output</strong></span></td>
<td class="tcat" style="width:10%"><span class="smalltext"><strong>Notes</strong></span></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[b]</span>This text is bold<span style="font-weight: bold; color: #ff0000;">[/b]</span></td>
<td class="trow1"><span style="font-weight: bold;" class="mycode_b">This text is bold</span></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[i]</span>This text is italicized<span style="font-weight: bold; color: #ff0000;">[/i]</span></td>
<td class="trow2"><span style="font-style: italic;" class="mycode_i">This text is italicized</span></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[u]</span>This text is underlined<span style="font-weight: bold; color: #ff0000;">[/u]</span></td>
<td class="trow1"><span style="text-decoration: underline;" class="mycode_u">This text is underlined</span></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[s]</span>This text is struck out<span style="font-weight: bold; color: #ff0000;">[/s]</span></td>
<td class="trow2"><span style="text-decoration: line-through;" class="mycode_s">This text is struck out</span></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[url]</span>http://www.example.com/<span style="font-weight: bold; color: #ff0000;">[/url]</span></td>
<td class="trow1"><a href="http://www.example.com/" class="mycode_url" rel="nofollow">http://www.example.com/</a></td>
<td class="trow1">URLs will auto-link if proper protocol is included (vaild protocols are http, https, ftp, news, irc, ircs and irc6).</td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[url=http://www.example.com/]</span>Example.com<span style="font-weight: bold; color: #ff0000;">[/url]</span></td>
<td class="trow2"><a href="http://www.example.com/" class="mycode_url" rel="nofollow">Example.com</a></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[email]</span>example@example.com<span style="font-weight: bold; color: #ff0000;">[/email]</span></td>
<td class="trow1"><a href="mailto:example@example.com" class="mycode_email">example@example.com</a></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[email=example@example.com]</span>E-mail Me!<span style="font-weight: bold; color: #ff0000;">[/email]</span></td>
<td class="trow2"><a href="mailto:example@example.com" class="mycode_email">E-mail Me!</a></td>
<td class="trow2">A subject can be included by adding <strong>?subject=Subject Here</strong> after the email address.</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[quote]</span>Quoted text will be here<span style="font-weight: bold; color: #ff0000;">[/quote]</span></td>
<td class="trow1"><blockquote class="mycode_quote"><cite>Quote:</cite>Quoted text will be here</blockquote></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[quote=\'Admin\' pid=\'1\' dateline=\'946684800\']</span>Quoted text will be here<span style="font-weight: bold; color: #ff0000;">[/quote]</span></td>
<td class="trow2"><blockquote class="mycode_quote"><cite><span> (01-01-2000, 12:00 AM)</span>Admin Wrote:  <a href="http://www.example.com/showthread.php?pid=1#pid1" class="quick_jump" rel="nofollow"></a></cite>Quoted text will be here</blockquote></td>
<td class="trow2">This format is used when quoting posts. <strong>pid</strong> links to a post, <strong>dateline</strong> is a <a href="https://www.unixtimestamp.com/">UNIX timestamp</a>.</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[code]</span>Text with preserved formatting<span style="font-weight: bold; color: #ff0000;">[/code]</span></td>
<td class="trow1"><div class="codeblock"><div class="title">Code:</div><div class="body" dir="ltr"><code>Text with preserved formatting</code></div></div></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[php]</span>&lt;?php echo "Hello world!";?&gt;<span style="font-weight: bold; color: #ff0000;">[/php]</span></td>
<td class="trow2"><div class="codeblock phpcodeblock"><div class="title">PHP Code:</div><div class="body"><div dir="ltr"><code><span style="color: #0000BB">&lt;?php&nbsp;</span><span style="color: #007700">echo&nbsp;</span><span style="color: #DD0000">"Hello&nbsp;world!"</span><span style="color: #007700">;</span><span style="color: #0000BB">?&gt;</span></code></div></div></div></div></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[img]</span>https://secure.php.net/images/php.gif<span style="font-weight: bold; color: #ff0000;">[/img]</span></td>
<td class="trow1"><img src="https://secure.php.net/images/php.gif" class="mycode_img"></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[img=50x50]</span>https://secure.php.net/images/php.gif<span style="font-weight: bold; color: #ff0000;">[/img]</span></td>
<td class="trow2"><img src="https://secure.php.net/images/php.gif" width="50" height="50" class="mycode_img"></td>
<td class="trow2">Format is width x height</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[color=red]</span>This text is red<span style="font-weight: bold; color: #ff0000;">[/color]</span></td>
<td class="trow1"><span style="color: red;" class="mycode_color">This text is red</span></td>
<td class="trow1">Can use either <a href="https://www.w3schools.com/cssref/css_colors.asp">CSS color name</a> or HEX code.</td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[size=large]</span>This text is large<span style="font-weight: bold; color: #ff0000;">[/size]</span></td>
<td class="trow2"><span style="font-size: large" class="mycode_size">This text is large</span></td>
<td class="trow2">Acceptable values: xx-small, x-small, small, medium, large, x-large, xx-large</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[size=30]</span>This text is 30px<span style="font-weight: bold; color: #ff0000;">[/size]</span></td>
<td class="trow1"><span style="font-size: 30px" class="mycode_size">This text is 30px</span></td>
<td class="trow1">Accepts number from 1 to 50</td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[font=Impact]</span>This font is Impact<span style="font-weight: bold; color: #ff0000;">[/font]</span></td>
<td class="trow2"><span style="font-family: Impact;" class="mycode_font">This font is Impact</span></td>
<td class="trow2">Font must be installed on your computer</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[align=center]</span>This is centered<span style="font-weight: bold; color: #ff0000;">[/align]</span></td>
<td class="trow1"><div style="text-align: center;" class="mycode_align">This is centered</div></td>
<td class="trow1">Acceptable values: left, center, right, justify</td>
</tr>
<tr>
<td class="trow2"><span style="font-weight: bold; color: #ff0000;">[list]</span><br />[*]List Item #1<br />[*]List Item #2<br />[*]List Item #3<br /><span style="font-weight: bold; color: #ff0000;">[/list]</span></td>
<td class="trow2"><ul class="mycode_list"><li>List item #1</li><li>List item #2</li><li>List Item #3</li></ul></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[list=1]</span><br />[*]List Item #1<br />[*]List Item #2<br />[*]List Item #3<br /><span style="font-weight: bold; color: #ff0000;">[/list]</span></td>
<td class="trow1"><ol class="mycode_list" type="1"><li>List item #1</li><li>List item #2</li><li>List Item #3</li></ol></td>
<td class="trow1"><strong>1</strong> can be used for a numbered list, <strong>a</strong> can be used for an alphabetical list, <strong>i</strong> for a roman numerals list.</td>
</tr>
<tr>
<td class="trow2">A line that<span style="font-weight: bold; color: #ff0000;">[hr]</span>divides</td>
<td class="trow2">A line that<hr class="mycode_hr">divides</td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: bold; color: #ff0000;">[video=youtube]</span>https://www.youtube.com/watch?v=dQw4w9WgXcQ<span style="font-weight: bold; color: #ff0000;">[/video]</span></td>
<td class="trow1"><iframe src="//www.youtube.com/embed/dQw4w9WgXcQ" allowfullscreen="" width="460" height="255" frameborder="0"></iframe></td>
<td class="trow1">Currently accepts Dailymotion, Facebook, LiveLeak, Metacafe, Mixer, MySpace TV, Twitch, Vimeo, Yahoo Videos and YouTube.</td>
</tr>
</tbody></table>
<br /><br />In addition, administrators may have created more MyCodes for use. Please contact an administrator to find out if there are any and on how to use them.';
