<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 02:40:09 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = 'Private Messages';
$l['nav_send'] = 'Compose';
$l['nav_tracking'] = 'Message Tracking';
$l['nav_folders'] = 'Folder Management';
$l['nav_empty'] = 'Empty Folders';
$l['nav_export'] = 'Export Messages';
$l['nav_search'] = 'Search';
$l['nav_results'] = 'Results';
$l['new_pm'] = 'New Message';
$l['old_pm'] = 'Old Message';
$l['reply_pm'] = 'Replied To';
$l['fwd_pm'] = 'Forwarded Message';
$l['pms_disabled'] = 'You cannot use the private messaging functionality as it has been disabled by the Administrator.';
$l['private_messaging'] = 'Private Messaging';
$l['inbox'] = 'Inbox';
$l['compose_message2'] = 'Compose Message';
$l['manage_folders'] = 'Manage Folders';
$l['pm_search_results'] = 'Private Message Search Results';
$l['message_title'] = 'Message Title';
$l['sender'] = 'Sender';
$l['sentto'] = 'Sent To';
$l['date_sent'] = 'Date/Time Sent';
$l['desc'] = 'desc';
$l['asc'] = 'asc';
$l['delete_pm'] = 'Delete';
$l['move_to'] = 'Move To';
$l['or'] = 'or';
$l['selected_messages'] = 'the selected messages';
$l['go'] = 'Go!';
$l['pmspaceused'] = 'of PM space used.';
$l['jump_folder'] = 'Jump to Folder:';
$l['archive_messages'] = 'Export Private Messages';
$l['archive_note'] = 'The following tool will let you mass download your private messages out of a selected folder, messages sent after a particular date, your read messages, and drafted messages for later viewing.';
$l['folders'] = 'Folders:';
$l['all_folders'] = 'All Folders';
$l['date_limit'] = 'Date Limitation:';
$l['date_limit_older'] = 'Export messages older than';
$l['date_limit_newer'] = 'Export messages newer than';
$l['date_limit_disregard'] = 'Disregard date';
$l['date_limit_days'] = 'days';
$l['export_unread'] = 'Export Unread Messages?';
$l['delete_archived'] = 'Delete Exported Messages?';
$l['delete_archived_note'] = 'Do you want to delete the messages from your folders once they have been exported?';
$l['export_format'] = 'Export File Format:';
$l['export_format_note'] = 'Please choose the file type of which to download attachments.';
$l['export_html'] = 'HTML File (.html)';
$l['export_txt'] = 'Text File (.txt)';
$l['export_csv'] = 'Importable MS Excel File (.csv)';
$l['private_messages_for'] = 'Private Messages for {1}';
$l['exported_date'] = 'Exported: {1}, {2}';
$l['subject'] = 'Subject:';
$l['to'] = 'To:';
$l['from'] = 'From:';
$l['sent'] = 'Sent:';
$l['export_messages2'] = 'Download Messages';
$l['empty_folders'] = 'Empty Private Messaging Folders';
$l['empty_folders2'] = 'Empty Folders';
$l['empty_note'] = 'Here you can delete private messages from selected folders at one time. Simply select the folders you wish the messages to be deleted from and click \'Delete\'. You cannot undo these changes.<br /><strong>Note: Once these messages are deleted there is no way to recover them.</strong>';
$l['num_messages'] = 'Message Count';
$l['empty_q'] = 'Empty Folder?';
$l['keep_unread'] = 'Keep Unread Messages';
$l['pm_folders'] = 'Private Messaging Folders';
$l['existing_folders'] = 'Existing Folders';
$l['edit_folder_note'] = 'You can change the names of your current private messaging folders here. To delete a folder, delete the name of the folder. Some folders cannot be removed.<br /><strong>Note: Deleting a folder will also delete any messages in it.</strong>';
$l['new_folders'] = 'Add New Folders';
$l['add_folders_note'] = 'Here you can create additional message folders. You do not have to fill in all of the text boxes.';
$l['update_folders'] = 'Update Folders';
$l['cannot_be_removed'] = 'Cannot be removed';
$l['reached_warning'] = 'Warning. You have reached your message limit.';
$l['reached_warning2'] = 'To be able to receive messages you will need to delete old messages.';
$l['deny_receipt'] = '[Deny Receipt]';
$l['viewing_pm'] = 'Viewing PM:';
$l['reply'] = 'Reply';
$l['reply_to_all'] = 'Reply to All';
$l['forward'] = 'Forward';
$l['compose_pm'] = 'Compose a Private Message';
$l['compose_to'] = 'Recipients:';
$l['compose_bcc'] = 'BCC:';
$l['compose_bcc_show'] = 'BCC';
$l['compose_bcc_show_title'] = 'Show the BCC input box allowing you to blind carbon copy messages to other users.';
$l['separate_names'] = 'Separate multiple user names with a comma.';
$l['max_recipients'] = '<br />You may send this message to a maximum of <strong>{1}</strong> people.';
$l['compose_subject'] = 'Subject:';
$l['compose_message'] = 'Message:';
$l['compose_options'] = 'Options:';
$l['message_icon'] = 'Message Icon:';
$l['options_sig'] = '<strong>Signature:</strong> include your signature in this message.';
$l['options_disable_smilies'] = '<strong>Disable Smilies:</strong> disable smilies from showing in this message.';
$l['options_save_copy'] = '<strong>Save a Copy:</strong> save a copy of this message in your Sent Items folder.';
$l['options_read_receipt'] = '<strong>Request Read Receipt:</strong> receive a message when this message is read.';
$l['send_message'] = 'Send Message';
$l['save_draft'] = 'Save as Draft';
$l['preview'] = 'Preview';
$l['select_buddy'] = 'Or Select a Buddy:';
$l['pm_tracking'] = 'Private Message Tracking';
$l['read_messages'] = 'Read Messages';
$l['unread_messages'] = 'Unread Messages';
$l['q'] = '?';
$l['dateread'] = 'Date Read';
$l['stop_tracking'] = 'Stop Tracking';
$l['datesent'] = 'Date Sent';
$l['cancel'] = 'Cancel';
$l['export_date_sent'] = 'Date';
$l['export_folder'] = 'Folder';
$l['export_subject'] = 'Subject';
$l['export_to'] = 'To';
$l['export_from'] = 'From';
$l['export_message'] = 'Message';
$l['not_sent'] = 'N/A (not sent)';
$l['at'] = 'at';
$l['nomessages'] = 'There are no private messages in this folder.';
$l['details'] = 'Details';
$l['message'] = 'Message';
$l['buddy_list'] = 'Buddy List';
$l['multiple_recipients'] = '<em>Multiple recipients</em>';
$l['bcc'] = 'BCC:';
$l['reply_title'] = 'Reply to this private message';
$l['forward_title'] = 'Forward this private message to another user';
$l['delete_title'] = 'Delete this private message';
$l['you_replied_on'] = 'You replied to this message on {1}';
$l['you_forwarded_on'] = 'You forwarded this message on {1}';
$l['you_replied'] = 'You replied to this message {1}';
$l['you_forwarded'] = 'You forwarded this message {1}';
$l['select_from_buddies'] = 'Select from Buddies';
$l['no_readmessages'] = 'You currently do not have any read messages being tracked.';
$l['no_unreadmessages'] = 'You currently do not have any unread messages being tracked.';
$l['stop_tracking_all'] = 'Stop Tracking all messages';
$l['enter_keywords'] = 'Enter Keywords';
$l['advanced_search'] = 'Advanced Search';
$l['search_pms'] = 'Search PMs';
$l['advanced_private_message_search'] = 'Advanced Private Message Search';
$l['search_criteria'] = 'Search Criteria';
$l['keywords'] = 'Keywords';
$l['search_in_subject'] = 'Search in Subject';
$l['search_in_message'] = 'Search in Message';
$l['message_status'] = 'Message Status';
$l['message_status_new'] = 'New';
$l['message_status_replied_to'] = 'Replied to';
$l['message_status_forwarded'] = 'Forwarded';
$l['message_status_read'] = 'Read';
$l['folder'] = 'Folder';
$l['search_options'] = 'Search Options';
$l['sort_by'] = 'Sort By';
$l['sort_by_subject'] = 'Sort By: Subject';
$l['sort_by_sender'] = 'Sort By: Sender';
$l['sort_by_date'] = 'Sort By: Date';
$l['ascending_order'] = 'Ascending Order';
$l['descending_order'] = 'Descending Order';
$l['search_private_messages'] = 'Search Private Messages';
$l['check_all'] = 'Check All';
$l['error_nopmsarchive'] = '죄송하지만 지정한 기준과 일치하는 개인 메시지가 없습니다.';
$l['error_invalidpmfoldername'] = '죄송하지만 입력한 폴더 이름에 허용되지 않는 문자가 포함되어 있습니다.';
$l['error_emptypmfoldername'] = '죄송합니다. 입력한 폴더 이름에 텍스트가 없습니다. 폴더 이름을 입력하거나 이름을 완전히 비워 폴더를 삭제하십시오.';
$l['error_invalidpmrecipient'] = '입력한 수신자가 잘못되었거나 없습니다. 다시 돌아가서 올바른 수신자를 입력하십시오.';
$l['error_invalidmovefid'] = '메시지를 이동하려는 폴더가 잘못되었습니다. 돌아가서 다시 시도하십시오.';
$l['error_invalidpm'] = 'Invalid PM';
$l['error_pmrecipientreachedquota'] = '{1}(으)로 개인 메시지를 보낼 수 없습니다. 메시지가 지워질 때까지 메시지를 보낼 수 없습니다. 이에 대한 이메일이 사용자에게 전송되었습니다. 나중 단계에서 메시지를 보내십시오.';
$l['error_recipientpmturnedoff'] = '{1}이(가) 개인 메시지를 수신하지 않기로 선택했거나 수신할 수 없습니다. 따라서 이 사용자에게 개인 메시지를 보낼 수 없습니다.';
$l['error_pmsturnedoff'] = '현재 프로필에서 개인 메시지가 비활성화되어 있습니다.<br />개인 메시지 시스템을 사용하려면 이 설정을 활성화해야 합니다.';
$l['error_recipientignoring'] = '죄송하지만 {1}에 대한 개인 메시지를 처리할 수 없습니다. 이 작업을 수행할 권한이 없습니다.';
$l['error_pm_already_submitted'] = '최근 5시간 이내에 동일한 개인 메시지를 동일한 수신자에게 이미 제출했습니다.';
$l['error_nopms'] = '이 기능에 액세스하려면 하나 이상의 개인 메시지가 있어야 합니다.';
$l['error_minsearchlength'] = '검색어 중 하나 이상이 최소 길이보다 짧습니다. 최소 검색어 길이는 {1}자입니다.<br /><br />전체 구문을 검색하려고 하면 큰따옴표로 둘러싸십시오. 예를 들어, "The quick brown fox jumps over the lazy dog."';
$l['error_nosearchresults'] = '죄송합니다. 제공한 쿼리 정보를 사용하여 결과가 반환되지 않았습니다. 검색어를 다시 정의하고 다시 시도하십시오.';
$l['error_no_search_support'] = '이 데이터베이스 엔진은 검색을 지원하지 않습니다.';
$l['error_nosearchterms'] = '검색어를 입력하지 않았습니다. 최소한 검색어를 입력하거나 검색할 사용자 이름을 입력해야 합니다.';
$l['error_searchflooding_1'] = '죄송합니다. {1}초마다 한 번의 검색만 수행할 수 있습니다. 다시 검색을 시도하기 전에 1초를 더 기다려 주십시오.';
$l['error_searchflooding'] = '죄송합니다. {1}초마다 한 번의 검색만 수행할 수 있습니다. 다시 검색을 시도하기 전에 {2}초를 더 기다려 주십시오.';
$l['error_invalidsearch'] = '잘못된 검색을 지정했습니다. 다시 돌아가 다시 시도하십시오.';
$l['redirect_pmsaved'] = '개인 메시지가 초안 폴더에 저장되었습니다.';
$l['redirect_pmstrackingstopped'] = '선택한 PM의 추적이 중지되었습니다.';
$l['redirect_pmstrackingcanceled'] = '선택한 읽지 않은 PM이 수신인의 받은 편지함에서 삭제되었습니다.';
$l['redirect_allpmstrackingstopped'] = 'Tracking of all read PMs has been stopped.';
$l['redirect_pmsmoved'] = 'The selected private messages have been moved.';
$l['redirect_pmsdeleted'] = 'The selected private messages have been deleted.';
$l['redirect_pmsent'] = 'Thank you, your private message has successfully been sent.<br />You will now be returned to your private message inbox.';
$l['redirect_pmfoldersupdated'] = '감사합니다. 개인 메시지 폴더가 성공적으로 업데이트되었습니다.<br />이제 개인 메시지 받은 편지함으로 돌아갑니다.';
$l['redirect_pmfoldersemptied'] = '선택한 개인 메시지 폴더를 비웠습니다.<br />이제 개인 메시지 받은 편지함으로 다시 이동됩니다.';
$l['redirect_searchresults'] = '감사합니다, 검색이 제출되었고 이제 결과 목록으로 이동됩니다.';
$l['quick_reply'] = '빠른 답장';
$l['message_note'] = '이 메시지에 대한 회신을 여기에 입력합니다.';
$l['send_reply'] = '답장 전송';
$l['quickreply_signature'] = 'Signature';
$l['quickreply_disable_smilies'] = 'Disable Smilies';
$l['quickreply_save_copy'] = 'Save a Copy';
$l['quickreply_read_receipt'] = 'Request Read Receipt';
