<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어
// Author of the language pack : whatthesamuel
// Language pack translators website : https://whatthesamuel.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : whatthesamuel
// Last edited date : Mon, 19 Feb 2024 03:22:43 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = '새 제목을 입력하지 않았습니다.';
$l['post_moderation'] = '귀하의 게시물은 현재 조정 중입니다.';
$l['thread_moderation'] = '스레드가 조정 중입니다.';
$l['post_doesnt_exist'] = '지정한 게시물이 없습니다.';
$l['thread_doesnt_exist'] = '지정한 스레드가 없습니다.';
$l['thread_closed_edit_subjects'] = '이 스레드는 닫혔으며 제목을 편집할 수 없습니다.';
$l['no_permission_edit_subject'] = '이 스레드 제목을 편집할 수 있는 권한이 없습니다.';
$l['thread_closed_edit_message'] = '이 스레드는 닫혔으며 해당 스레드에서 메시지를 편집할 수 없습니다.';
$l['no_permission_edit_post'] = '이 메시지를 편집할 권한이 없습니다.';
$l['edit_time_limit'] = '메시지가 게시된 후 {1}분 동안만 편집할 수 있습니다.';
$l['postbit_edited'] = '이 게시물이 마지막으로 수정되었습니다. {1}';
$l['postbit_editreason'] = '편집 사유';
$l['save_changes'] = '저장';
$l['cancel_edit'] = '수정 취소';
$l['answer_valid_not_exists'] = '답변하려는 질문이 없습니다.';
$l['captcha_not_exists'] = '새로고침하려는 이미지 확인 이미지가 없습니다.';
$l['captcha_valid_not_exists'] = '확인하려는 이미지 확인 이미지가 존재하지 않는 것 같습니다.';
$l['captcha_does_not_match'] = '입력하신 이미지 확인 코드가 잘못되었습니다. 이미지에 표시된 코드를 정확히 입력하십시오.';
$l['captcha_matches'] = '입력하신 이미지 확인 코드는 정확했습니다.';
$l['answer_does_not_match'] = '입력하신 답변이 정확하지 않습니다.';
$l['banned_username'] = '입력한 사용자 이름이 관리자에 의해 허용되지 않음';
$l['banned_characters_username'] = '사용자 이름에 잘못된 문자가 하나 이상 포함되어 있습니다';
$l['complex_password_fails'] = '암호에는 대문자, 소문자 및 숫자가 필요합니다';
$l['username_taken'] = '{1}이(가) 이미 다른 구성원에 의해 등록되었습니다';
$l['username_available'] = '{1}을(를) 사용할 수 있습니다';
$l['invalid_username'] = '{1}은(는) 등록된 구성원의 사용자 이름이 아닙니다';
$l['valid_username'] = '{1}은(는) 유효한 추천인입니다.';
$l['buddylist_error'] = '친구 목록에 친구가 없는 것 같습니다. 이것을 사용하기 전에 추가하십시오.';
$l['close'] = '닫기';
$l['select_buddies'] = '친구 선택';
$l['select_buddies_desc'] = '하나 이상의 친구를 수신인으로 추가하려면 아래에서 친구를 선택한 후 [확인]을 누릅니다.';
$l['selected_recipients'] = 'Selected recipients';
$l['ok'] = '확인';
$l['cancel'] = '취소';
$l['online'] = '온라인';
$l['offline'] = '오프라인';
$l['edited_post'] = '수정된 게시글';
$l['usergroup'] = '유저 그룹';
